import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import style from '@/views/Home/style.module.scss';
import Slide from '@/views/Home/Slide';
import { GetMainMenu } from './api/CallAPI';
import Service from '@/views/Home/Service';
import MapCustomer from '@/views/Home/MapCustomer';
import Product from '@/views/Home/Product';
import About from '@/views/Home/About';
import Smartwork from '@/views/Home/Smartwork';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const mainMenu = GetMainMenu();

  return (
    <>
      <Head>
        <title>Information - Intelliegent - Innovation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slide/>
        <About/>
        <Smartwork/>
        {mainMenu.data && <Product data={ mainMenu.data[1].children}/>}
        {mainMenu.data && <Service data={ mainMenu.data[2].children}/>}
        <MapCustomer/>
      </main>
    </>
  )
}
